### ISSUE TITLE
Text with formatting error

### ISSUE THREAD

**Issue by Uitalo** [ijgnd/anki__editor_jseditor_for_current_field#2]
I believe that after the last update: "- 2020-02-07 remember the window size, update packaged in packages", caused that after editing a table the text does not adapt to the new format of the table, which it's a little inconvenient.

![image](https://user-images.githubusercontent.com/13296083/76172614-8e521280-6176-11ea-8d67-e3a620fbebce.png)

**Comment by ijgnd** [comment]
I somehow missed your issue. Today I updated the add-on and now I use a much more modern editor component. Could you update and try again. Does the problem persist?

**Comment by davidagiraldo** [comment]
Thank you so much for the help! Ok I’ll try that and get back to you.

All the best!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ijgnd** [comment]
If you have the problem again let me know.
