### ISSUE TITLE
T5 editor doesn't work in anki 2.1.21

### ISSUE THREAD

**Issue by izanagiii** [ijgnd/anki__editor_jseditor_for_current_field#3]
Hi
Thanks for this add-on

Unfortunately after the last update T5 editor doesn't work in anki 2.1.21
![image](https://user-images.githubusercontent.com/59202302/83364360-1e8aa700-a3b6-11ea-985e-a79a8f455be8.png)

Thanks in advance

**Comment by ijgnd** [comment]
Thanks for reporting this.

Unfortunately I can't reproduce this bug. So I need your help. 

From the main window click on Help->About. In the window that opens click the "Copy Debug Info" Button and share the copied text.

Could you disable all other add-ons restart Anki and try again: Does the problem persist?

Could you maybe delete my add-on and then reinstall from https://ankiweb.net/shared/info/805891399 : Does this change anything?



btw: The old version can be downloaded from [here](https://github.com/ijgnd/anki__editor_jseditor_for_current_field/releases/download/0.1/extended_.table._editor__old_v4__2020-04-28.ankiaddon) and installed with drag&drop into the add-on window.

**Comment by izanagiii** [comment]
Don't mention it you're the one doing all the work here

1. I disabled all add-ons but T5 & the problem still persist

2. after deleting & reinstalling your add-on still not luck on the problem

3. when I hit "save" button get this error:
`Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.21 (f1734a47) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-06-01 02:03:03

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 368, in handler
  File "aqt\editor.py", line 443, in <lambda>
  File "C:\Users\He Who Doesn't Speak\AppData\Roaming\Anki2\addons21\805891399\external_js_editor_for_field.py", line 271, in <lambda>
    editor.saveNow(lambda e=editor: _onWYSIWYGUpdateField(e))
  File "C:\Users\He Who Doesn't Speak\AppData\Roaming\Anki2\addons21\805891399\external_js_editor_for_field.py", line 265, in _onWYSIWYGUpdateField
    editor.note.flush()
  File "lib\site-packages\anki\notes.py", line 85, in flush
  File "lib\site-packages\anki\utils.py", line 176, in stripHTMLMedia
TypeError: expected string or bytes-like object
`
[Error info.txt](https://github.com/ijgnd/anki__editor_jseditor_for_current_field/files/4709450/Error.info.txt)

4. here is my debug info (from help>about):
[Debug Info.txt](https://github.com/ijgnd/anki__editor_jseditor_for_current_field/files/4709456/Debug.Info.txt)

Thanks again for your time & contribution

**Comment by ijgnd** [comment]
I have another report that it doesn't work but I got no further info. So I suspect that it's a widespread problem that I'd like to have solved ...

Could you install this custom version and restart Anki from the commandline [1]: https://github.com/ijgnd/anki__editor_jseditor_for_current_field/releases/download/0.2/anki__editor_jseditor_for_current_field__2020-06-01_load_later.ankiaddon

video: [installing ankiaddon files from outside of ankiweb](https://raw.githubusercontent.com/glutanimate/docs/master/anki/add-ons/media/ankiaddon-installation.gif)

After installing and restarting Anki: Go to an Add window and open the external editor window. Then copy the output that Anki has printed into the cmd window and share it here.

Does this modified version work?


[1] How to start anki from the commandline in Windows:

- search the start menu for "cmd", click on it. A new window where you can type in text should open
- in the window explorer go to `C:\Program Files\Anki\`. From this folder drag and drop the file `anki-console.exe` onto the cmd window. The full path should appear in it like so: `C:\Program Files\Anki\anki-console.exe`. Put the focus on the cmd window and press the enter/return key to run this command. Then Anki should start and you should see a lot of lines printed  in the cmd window. I need the bottom of this output.

**Comment by izanagiii** [comment]
I deleted the add-on & installed the modified version you provided with the link:

the error when opened the modified version from add windows is:

[Error modified version.txt](https://github.com/ijgnd/anki__editor_jseditor_for_current_field/files/4711044/Error.modified.version.txt)

**Comment by ijgnd** [comment]
Strange. I still have no idea. My javascript are very limited. It seems that the tinymce component is not available whereas in my windows 10 with anki 2.1.21 it works ...

Another idea: could you install this version: https://github.com/ijgnd/anki__editor_jseditor_for_current_field/releases/download/0.2/805891399.ankiaddon

Run it again from the command line.

Does this work?

in the cmd window after opening the window you should get some output like this:

    _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-fieldcontent
    http://127.0.0.1:50714/_addons/805891399/web/tinymce5/js/tinymce/tinymce.min.js

Yours will look slightly different. Copy the http address and and try to open it in your browser chrome/firefox/edge: Can you open this file and do you see a file of javascript code that starts with 

```
/**
 * Copyright (c) Tiny Technologies, Inc. All rights reserved.
 * Licensed under the LGPL or a commercial license.
 * For LGPL see License.txt in the project root for license information.
 * For commercial licenses see https://www.tiny.cloud/
 *
...
```



if you are interested: You can now debug the webviews using an external Chrome instance, by setting the env var QTWEBENGINE_REMOTE_DEBUGGING to 8080 prior to starting Anki, then surfing to localhost:8080 in Chrome.

so you need to run `set QTWEBENGINE_REMOTE_DEBUGGING=8080` in cmd before you run anki-console.

**Comment by izanagiii** [comment]
1. The last file you provided solved the issue (805891399.ankiaddon)

2. I added the env var as you mentioned & here it is the output:
```
qt: Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:8080
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-fieldcontent
http://127.0.0.1:4172/_addons/805891399/web/tinymce5/js/tinymce/tinymce.min.js
```

3. Opened the tinymce.min.js file inside chrome and Yes the code was correct:
This is the file:
[tinymce.min.zip](https://github.com/ijgnd/anki__editor_jseditor_for_current_field/files/4714039/tinymce.min.zip)

4. I don't know what caused the problem with the version provided on official add-on page but since the file you provided works well that good enough for me but if you need further error information to resolve the issue with the official file I am more than happy to help


Thanks for your time & patience

**Comment by ijgnd** [comment]
The source of the problem seems to be the line [124 of the file external_js_editor_for_field.py](https://github.com/ijgnd/anki__editor_jseditor_for_current_field/blob/69a12d2dbf0103773bd297d1479957087c96ae8e/src/external_js_editor_for_field.py#L124).

The code that is shown in github and the code from the file "805891399.ankiaddon" is:

    regex = r"(web.*)"

On Ankiweb I have 

    regex = r"(web/.*)"

with an additional slash at the end. It makes sense that this doesn't work on Windows. But since it worked on my Windows 10 I figured that it should work on other Windows 10 installations, too.

To make sure that this is the problem could you change the line back with an additional slash to and try if it fails: 

    regex = r"(web/.*)"

Then also try the following and let me know if it works:

    regex = r"(web[/\\].*)"

Your detailed reports were indispensable in figuring this out.

To get to the file "external_js_editor_for_field.py": In the add-on manager (main window -> Tools -> Add-ons) select this addon, then click the button "view files", then you should see the file "external_js_editor_for_field.py" in windows explorer (or whatever file manager you use). Then edit it with a text editor like notepad.

**Comment by izanagiii** [comment]
Oh interesting so the problem was lack of support for (/) in windows 

Yeah, I will edit the file with the change you provided.

Thanks a lot for solving the issue 
I'm grateful to you for your support
