### ISSUE TITLE
Problem if note is opened in Ankidroid

### ISSUE THREAD

**Issue by eu2021** [ijgnd/anki__editor_jseditor_for_current_field#8]
This a follow up from [this](https://forums.ankiweb.net/t/extended-editor-for-field-for-tables-search-replace-official-thread/552/27?u=davidcortez).

So, the step by step:

1. In the PC Anki, create a note (cloze type) and use the addon to edit one of the fields. Eg, this note:

![before](https://user-images.githubusercontent.com/77707706/122646370-29b19180-d0f5-11eb-84d1-6c80eca2e783.png)

And this is the html:
```
<p>c</p>
<p>d</p>
```

2. Open this note in Ankidroid. Close (no need to make changes). I will already see that the card changed.
3. Back to the PC Anki, the note is now like this:
![after](https://user-images.githubusercontent.com/77707706/122646517-ed326580-d0f5-11eb-9d3e-bf29cae88ffb.png)

And this is the code:
```
<p>c</p><br><p>d</p>
```
---------
I also tried: creating a card with the html generated using [Full featured examples | Docs | TinyMCE](https://www.tiny.cloud/docs/demo/full-featured/) and the result is the same.

Thanks,

**Comment by eu2021** [comment]
Actually, I just found that this problem happens with tables that are inserted by any means on Anki. I tested with a table from https://www.tablesgenerator.com/html_tables , and with the addon [Add Table](https://ankiweb.net/shared/info/1237621971). So, I will report it in AnkiDroid instead.

**Comment by eu2021** [comment]
Ok, I just found it's an known bug in AnkiDroid [since 2015](https://github.com/ankidroid/Anki-Android/issues/3304).

**Comment by mikehardy** [comment]
Have you tried the new preference mentioned here? https://github.com/ankidroid/Anki-Android/pull/7692

**Comment by mikehardy** [comment]
noted as resolved in related ankidroid thread by enabling a setting (whew! :sweat_smile: )

**Comment by ijgnd** [comment]
@mikehardy: thanks for saving me time. Honestly I'm pretty relieved that my add-on (which allows to edit field contents in the wysiwyg editor TinyMCE) doesn't seem to be responsible for subtly breaking stuff. btw: thanks for all your work on Ankidroid.

@eu2021: It's great that you posted your troubleshooting results. At the moment I'm pretty busy and my knowledge about html and js is very limited so I postponed looking into this problem. I'm glad you've found a solution.
